listener 1883 0.0.0.0
allow_anonymous true

connection edge_to_cloud
address mqtt-broker:1883
# Inoltra tutti i messaggi pubblicati sui topic che iniziano con 'cloud/'
# verso il broker remoto. Il parametro 'out' indica la direzione (edge -> cloud)
topic cloud/# out 0