apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto-edge
  labels:
    app: mosquitto-edge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto-edge
  template:
    metadata:
      labels:
        app: mosquitto-edge
    spec:
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations:
        - key: "node-role.kubernetes.io/edge"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: mosquitto
          image: eclipse-mosquitto:latest
          ports:
            - containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto-edge.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-conf
---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-edge-service
spec:
  type: ClusterIP
  selector:
    app: mosquitto-edge
  ports:
    - port: 1883
      targetPort: 1883