apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-simulator
  labels:
    app: sensor-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sensor-simulator
  template:
    metadata:
      labels:
        app: sensor-simulator
    spec:
      initContainers:
        - name: wait-for-mqtt
          image: busybox:1.36
          # Esegue un loop che tenta di contattare la porta 1883 del servizio MQTT
          command:
            - 'sh'
            - '-c'
            - >
              echo "Verify connection broker MQTT...";
              until nc -z 172.25.0.2 1883; do
                echo "Broker MQTT not ready, retry in 3 seconds...";
                sleep 3;
              done;
              echo "Broker MQTT ready! Starting of the app.";
      nodeSelector:
        node-role.kubernetes.io/edge: ""
      tolerations:
        - key: "node-role.kubernetes.io/edge"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: sensor-simulator
          image: mronca56/device-simulation:latest
          imagePullPolicy: Always
          env:
            - name: BROKER_URL
              value: "tcp://172.25.0.2:1883"