apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceModel
metadata:
  name: camera-model
  namespace: default
spec:
  properties:
    - name: peopleCount
      type: INT
      accessMode: ReadWrite
    - name: queueLength
      type: INT
      accessMode: ReadWrite
    - name: suspiciosActivity
      type: STRING
      accessMode: ReadWrite
---
apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: camera-01
  namespace: default
spec:
  deviceModelRef:
    name: camera-model
  nodeName: edge-test
  protocol:
    protocolName: mqtt
    configData:
      url: "tcp://mosquitto-service:1883"