apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 1Gi                # Size of the volume
  accessModes:
    - ReadWriteOnce              # Only one node can mount at a time
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:                      # Local path for demo purposes
    path: /data/mongo

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi