apiVersion: devices.kubeedge.io/v1beta1
kind: DeviceModel
metadata:
  name: register-model
  namespace: default
spec:
  properties:
    - name: codeProduct
      type: INT
      accessMode: ReadWrite
    - name: quantity
      type: INT
      accessMode: ReadWrite
    - name: totalPrice
      type: DOUBLE
      accessMode: ReadWrite
---
apiVersion: devices.kubeedge.io/v1beta1
kind: Device
metadata:
  name: register-01
  namespace: default
spec:
  deviceModelRef:
    name: register-model
  nodeName: edge-test
  protocol:
    protocolName: mqtt
    configData:
      url: "tcp://mosquitto-service:1883"